clearversion: "3.9"
services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes: [mongo_data:/data/db]

  backend:
    build: ./docker/backend
    ports: ["8000:8000"]
    environment:
      MONGO_URI: mongodb://mongo:27017/studysync
    depends_on: [mongo]

  socket:
    build: ./docker/socket
    ports: ["4000:4000"]
    depends_on: [mongo]

  frontend:
    build: ./docker/frontend
    ports: ["5173:5173"]
    depends_on: [backend, socket]

volumes:
  mongo_data:
