services:
  - type: web
    name: studysync
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health/
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: MONGO_URI
        sync: false
