[supervisord]
nodaemon=true
[program:nginx]
command=nginx -g "daemon off;"
autorestart=true
[program:django]
directory=/app/backend
command=gunicorn studysync.wsgi:application --bind 127.0.0.1:8000 --workers 2
autorestart=true
[program:socket]
directory=/app/socket
environment=SOCKET_PORT="4000"
command=node server.js
autorestart=true
